# Generated by Django 3.2.6 on 2021-08-24 14:03

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ebook',
            fields=[
                ('bookid', models.AutoField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=200)),
                ('bookauthor', models.CharField(max_length=200)),
                ('bookdesc', models.CharField(max_length=1000)),
                ('tumbnail', models.ImageField(upload_to=home.models.book_directory_path, verbose_name='tumbnail')),
            ],
        ),
    ]
