# Generated by Django 3.2.6 on 2021-08-24 14:17

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='book',
            field=models.FileField(default='', upload_to=home.models.book_directory_path),
            preserve_default=False,
        ),
    ]
