# Generated by Django 3.2.6 on 2021-08-27 15:01

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ebook_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='tumbnail',
        ),
        migrations.AddField(
            model_name='ebook',
            name='Thumbnail',
            field=models.ImageField(default='', upload_to=home.models.book_directory_path, verbose_name='Thumbnail'),
            preserve_default=False,
        ),
    ]
