# Generated by Django 3.2.9 on 2021-11-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210827_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='Thumbnail',
            field=models.ImageField(upload_to='static/<function book_directory_path at 0x000001F29B3E79A0>', verbose_name='Thumbnail'),
        ),
    ]
