# Generated by Django 3.2.9 on 2021-11-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_ebook_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='Thumbnail',
            field=models.ImageField(upload_to='static/<function book_directory_path at 0x0000021077C779A0>', verbose_name='Thumbnail'),
        ),
    ]
